#!/bin/sh

# Set environment
export BSPWM_CONFIG="$HOME/.config/bspwm"

bspc config border_width        5
bspc config window_gap          5
bspc config top_padding         2

bspc config split_ratio                 0.50
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc desktop '^1' --layout monocle
bspc config history_aware_focus         true

bspc monitor --reset-desktops term www dev chat edit play virt 8 9 10

# just node floating BS
bspc subscribe node_manage | while read event monitor desktop nodeid ipid; do
	case "$desktop" in
		www|play|6|virt|7|9)
			bspc node "$nodeid" --state floating
			;;
	esac
done &

bspc rule --add Firefox                     desktop='www' follow=on
bspc rule --add Eclipse			    desktop='dev' follow=on
bspc rule --add mpv                         desktop='play' follow=on
bspc rule --add qemu-system-x86_64          desktop='virt' follow=on
bspc rule --add Virt-manager                desktop='virt' follow=on
bspc rule --add URxvt:popup                 state=floating
bspc rule --add Eog                         state=floating
bspc rule --add feh                         state=floating
bspc rule --add mpv                         state=floating
bspc rule --add Nautilus                    state=floating
bspc rule --add Pavucontrol                 state=floating
. "/usr/share/themes/colorschemes/bspwm.cfg"
bspc config focused_border_color            "$brightwhite"
bspc config active_border_color             "$brightblack"
bspc config normal_border_color             "$black"
bspc config urgent_border_color             "$blue"
bspc config presel_feedback_color           "$yellow"
bspc config focused_locked_border_color     "$brightred"
bspc config active_locked_border_color      "$red"
bspc config normal_locked_border_color      "$black"
bspc config focused_sticky_border_color     "$brightcyan"
bspc config active_sticky_border_color      "$cyan"
bspc config normal_sticky_border_color      "$black"
bspc config focused_private_border_color    "$brightblue"
bspc config active_private_border_color     "$blue"
bspc config normal_private_border_color     "$black"

hsetroot -solid "$brightblack"

sxhkd &

"$BSPWM_CONFIG/autostart" &

